# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'YKFSwift' do
  use_frameworks!

pod 'Alamofire'
pod 'MJRefresh'
pod 'SDCycleScrollView'
pod 'SDWebImage'
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources'
pod 'SwiftyJSON'

end
